# Generated by Django 5.0.4 on 2024-08-23 07:02

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_updated'),
    ]

    operations = [
        TrigramExtension()
    ]
